#!/bin/bash
#PBS -q debug
#PBS -l mppwidth=3076
#PBS -l walltime=00:30:00
#PBS -N gather_test
#PBS -o $PBS_JOBID.out
#PBS -j oe
#PBS -A m175
#PBS -V

cd $PBS_O_WORKDIR
export MPICH_MAX_THREAD_SAFETY multiple
export OMP_NUM_THREADS=12
make clean && make
aprun -n 128 -N 1 -cc none -d 12 ./main 35552
